
services:


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" 
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
